name: template-sync

on:
  # cronjob trigger at 03:00 every day.
  schedule:
  - cron:  "0 3 * * *"
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.6.0-draft
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          source_repo_path: ventx/stackx-template-terraform
          pr_labels: chore,template-sync
          pr_title: "chore: upstream merge template repository"
